/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/UTOjQJZrmjg
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'
import { Tenor_Sans } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

tenor_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function MainPage() {
  return (
    <div className="bg-background text-foreground">
      <header className="w-full py-12 md:py-20 lg:py-24">
        <div className="container grid gap-8 md:grid-cols-[1fr_400px] md:gap-12 lg:gap-16">
          <div className="space-y-4">
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">Delicious Vegan Recipes</h1>
            <p className="max-w-[600px] text-muted-foreground md:text-xl">
              Discover a world of plant-based deliciousness with our collection of mouthwatering vegan recipes.
            </p>
            <div className="relative max-w-md">
              <div className="absolute inset-y-0 left-2 flex items-center pl-2 pointer-events-none">
                <SearchIcon className="w-5 h-5 text-muted-foreground" />
              </div>
              <Input type="search" placeholder="Search recipes..." className="w-full pl-10 rounded-md" />
            </div>
          </div>
          <img
            src="/placeholder.svg"
            width={500}
            height={500}
            alt="Vegan Recipes"
            className="mx-auto rounded-lg object-cover aspect-square"
          />
        </div>
      </header>
      <main className="container grid gap-8 md:grid-cols-[1fr_300px] md:gap-12 lg:gap-16">
        <div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            <Card className="group">
              <CardContent className="p-0">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={300}
                  alt="Vegan Pasta"
                  className="rounded-t-lg object-cover aspect-[4/3] group-hover:opacity-80 transition-opacity"
                />
                <div className="p-4 space-y-2">
                  <h3 className="text-lg font-semibold">Creamy Vegan Pasta</h3>
                  <p className="text-muted-foreground line-clamp-2">
                    A delightful plant-based pasta dish with a creamy cashew-based sauce.
                  </p>
                </div>
              </CardContent>
            </Card>
            <Card className="group">
              <CardContent className="p-0">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={300}
                  alt="Vegan Burger"
                  className="rounded-t-lg object-cover aspect-[4/3] group-hover:opacity-80 transition-opacity"
                />
                <div className="p-4 space-y-2">
                  <h3 className="text-lg font-semibold">Juicy Vegan Burger</h3>
                  <p className="text-muted-foreground line-clamp-2">
                    A satisfying plant-based burger with a delicious homemade patty.
                  </p>
                </div>
              </CardContent>
            </Card>
            <Card className="group">
              <CardContent className="p-0">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={300}
                  alt="Vegan Salad"
                  className="rounded-t-lg object-cover aspect-[4/3] group-hover:opacity-80 transition-opacity"
                />
                <div className="p-4 space-y-2">
                  <h3 className="text-lg font-semibold">Refreshing Vegan Salad</h3>
                  <p className="text-muted-foreground line-clamp-2">
                    A vibrant and nourishing plant-based salad with a variety of fresh ingredients.
                  </p>
                </div>
              </CardContent>
            </Card>
            <Card className="group">
              <CardContent className="p-0">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={300}
                  alt="Vegan Tacos"
                  className="rounded-t-lg object-cover aspect-[4/3] group-hover:opacity-80 transition-opacity"
                />
                <div className="p-4 space-y-2">
                  <h3 className="text-lg font-semibold">Flavorful Vegan Tacos</h3>
                  <p className="text-muted-foreground line-clamp-2">
                    Delicious plant-based tacos with a variety of toppings and a zesty sauce.
                  </p>
                </div>
              </CardContent>
            </Card>
            <Card className="group">
              <CardContent className="p-0">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={300}
                  alt="Vegan Curry"
                  className="rounded-t-lg object-cover aspect-[4/3] group-hover:opacity-80 transition-opacity"
                />
                <div className="p-4 space-y-2">
                  <h3 className="text-lg font-semibold">Aromatic Vegan Curry</h3>
                  <p className="text-muted-foreground line-clamp-2">
                    A flavorful plant-based curry dish with a blend of spices and coconut milk.
                  </p>
                </div>
              </CardContent>
            </Card>
            <Card className="group">
              <CardContent className="p-0">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={300}
                  alt="Vegan Dessert"
                  className="rounded-t-lg object-cover aspect-[4/3] group-hover:opacity-80 transition-opacity"
                />
                <div className="p-4 space-y-2">
                  <h3 className="text-lg font-semibold">Decadent Vegan Dessert</h3>
                  <p className="text-muted-foreground line-clamp-2">
                    A rich and indulgent plant-based dessert that will satisfy your sweet tooth.
                  </p>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
        <div className="space-y-8">
          <Card>
            <CardHeader>
              <CardTitle>Categories</CardTitle>
            </CardHeader>
            <CardContent className="grid gap-2">
              <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
                Main Dishes
              </Link>
              <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
                Appetizers
              </Link>
              <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
                Desserts
              </Link>
              <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
                Salads
              </Link>
              <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
                Soups
              </Link>
              <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
                Snacks
              </Link>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Tags</CardTitle>
            </CardHeader>
            <CardContent className="grid gap-2">
              <Link
                href="#"
                className="inline-flex items-center gap-2 rounded-md bg-muted px-3 py-1 text-sm font-medium hover:bg-muted/80"
                prefetch={false}
              >
                <TagIcon className="w-4 h-4" />
                Gluten-free
              </Link>
              <Link
                href="#"
                className="inline-flex items-center gap-2 rounded-md bg-muted px-3 py-1 text-sm font-medium hover:bg-muted/80"
                prefetch={false}
              >
                <TagIcon className="w-4 h-4" />
                Nut-free
              </Link>
              <Link
                href="#"
                className="inline-flex items-center gap-2 rounded-md bg-muted px-3 py-1 text-sm font-medium hover:bg-muted/80"
                prefetch={false}
              >
                <TagIcon className="w-4 h-4" />
                Soy-free
              </Link>
              <Link
                href="#"
                className="inline-flex items-center gap-2 rounded-md bg-muted px-3 py-1 text-sm font-medium hover:bg-muted/80"
                prefetch={false}
              >
                <TagIcon className="w-4 h-4" />
                Whole Foods
              </Link>
              <Link
                href="#"
                className="inline-flex items-center gap-2 rounded-md bg-muted px-3 py-1 text-sm font-medium hover:bg-muted/80"
                prefetch={false}
              >
                <TagIcon className="w-4 h-4" />
                Quick
              </Link>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Newsletter</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              <p className="text-muted-foreground">
                Subscribe to our newsletter and be the first to know about our latest vegan recipes and updates.
              </p>
              <form className="flex gap-2">
                <Input type="email" placeholder="Enter your email" className="flex-1" />
                <Button type="submit">Subscribe</Button>
              </form>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}

function SearchIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function TagIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.586 2.586A2 2 0 0 0 11.172 2H4a2 2 0 0 0-2 2v7.172a2 2 0 0 0 .586 1.414l8.704 8.704a2.426 2.426 0 0 0 3.42 0l6.58-6.58a2.426 2.426 0 0 0 0-3.42z" />
      <circle cx="7.5" cy="7.5" r=".5" fill="currentColor" />
    </svg>
  )
}
